### ISSUE TITLE
xxv not listed on overview page

### ISSUE THREAD

**Issue by pbiering** [vdr-projects/xxv#1]
@M-Reimer :  xxv is not listed on https://vdr-projects.github.io, any reason?

**Comment by M-Reimer** [comment]
See #2. For me xxv is a project of unknown state. I don't know if it is still useful to anyone and I guess there are not many users either. I can not and do not want to link everything that arrived at the vdr-projects organization when projects.vdr-developer.org went down. Adding all of this, even if it is likely outdated or unused, would make the overview page pretty cluttered.

**Comment by pbiering** [comment]
understood, see https://github.com/vdr-projects/xxv/issues/2#issuecomment-1871211469
