### ISSUE TITLE
link to project's home page is broken

### ISSUE THREAD

**Issue by pbiering** [vdr-projects/xxv#2]
http://projects.vdr-developer.org/projects/xxv is broken, the whole content looks like gone, also the TLS cert is no longer matching FQDN

**Comment by M-Reimer** [comment]
Yep, that's the case for probably 90% of all projects on the "vdr-projects" organization.

Before "projects.vdr-developer.org" went down, I wrote some scripts to mirror all its repos to here. But this was a pure mirroring process. Nothing has been changed as it was still a possibility that the project owners decide to maintain their projects elsewhere. In this case the mirror here would have been configured as a "public archive" with a link to the actual new project home.

And I still don't plan to mass-update project URLs all across the organization. I'm pretty OK with the state that we have roughly four categories of projects:

1. Projects that are actually maintained by an active maintainer
2. Community maintained projects which are in active use and so are at least kept updated to keep working
3. Public archives where a new home of the project is known and so only a (non updated) mirror is kept here
4. Actual mirrors of projects with unknown state without knowledge if they build at all, are still used and/or are still useful to anyone.

I would put xxv in the 4th category.

**Comment by M-Reimer** [comment]
Or to put it straight: If you plan to work on xxv, I happily give you write permission to this repo and add it to the overview page. But before adding it to the list, it would be nice if you could at least make sure that it actually builds and works.

**Comment by pbiering** [comment]
@M-Reimer : 100% ack, I have no plans to use this, potentially at least this can be marked as "stale" somehow in "about" like

_STALE+UNMAINTAINED / only mirrored from nowadays EOL https://projects.vdr-developer.org/git/xxv.git/_
